[deploy]
preDeployCommand = "php artisan migrate --force"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
buildCommand = "COMPOSER_ALLOW_SUPERUSER=1 composer install --optimize-autoloader --no-interaction --no-scripts && npm ci && npm run build && php artisan config:cache && php artisan route:cache"
